import { prisma } from '@/lib/prisma'

export async function seedMaquinario() {
  const maquinario = [
    {
      name: 'TRATOR DE PNEUS - FARMAL 132',
      currentValue: 519000,
      status: 'quitado',
      owner: 'Romilda Silveira Rego',
      type: 'Trator',
      manufacturer: 'CASE',
      manufactureYear: 2019,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS',
      currentValue: 1094202,
      status: 'financiado',
      owner: 'Romilda Silveira Rego',
      type: 'Trator',
      manufacturer: 'JOHN DEERE',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom | Financeira: Clube Fx',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CARRETA AGRÍCOLA',
      currentValue: 4000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Carreta',
      manufacturer: 'SANTA CLARA',
      manufactureYear: 2001,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom | Financeira: FlorFinance',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'BENEFICIADORA DE GRÃOS',
      currentValue: 130000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Equipamento',
      manufacturer: 'MARCHER BRASIL',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS - 7040',
      currentValue: 350000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Trator',
      manufacturer: 'NEW HOLLAND',
      manufactureYear: 2011,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PULVERIZADOR PEC',
      currentValue: 6200,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Pulverizador',
      manufacturer: 'JACTO',
      manufactureYear: 2004,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PULVERIZADOR AUTOPROPELIDO',
      currentValue: 450000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Pulverizador',
      manufacturer: 'JACTO',
      manufactureYear: 2008,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'VEICULO UTILITÁRIO - COROLLA CROSS',
      currentValue: 205000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Veículo',
      manufacturer: 'TOYOTA',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TANQUE PIPA',
      currentValue: 6000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Tanque',
      manufacturer: 'FACCHINI',
      manufactureYear: 2013,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLATAFORMA COLHEITADEIRA',
      currentValue: 100000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Colheitadeira',
      manufacturer: 'NEW HOLLAND',
      manufactureYear: 2012,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CAMIONETE',
      currentValue: 60000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Veículo',
      manufacturer: 'CHEVROLET',
      manufactureYear: 1995,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'ARADO',
      currentValue: 5000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Arado',
      manufacturer: 'TATU',
      manufactureYear: 1979,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'DISTRIBUIDOR DE SEMENTES - VINCON',
      currentValue: 5000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Distribuidor',
      manufacturer: 'JAN',
      manufactureYear: 2005,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CARRETA AGRICOLA',
      currentValue: 10000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Carreta',
      manufacturer: 'MASAL',
      manufactureYear: 1992,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'DISTRIBUIDORA DE ADUBO',
      currentValue: 65000,
      status: '',
      owner: 'Romilda Silveira Rego',
      type: 'Distribuidor',
      manufacturer: 'MARCHER',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS',
      currentValue: 105316.05,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Trator',
      manufacturer: 'NEW HOLLAND 7630',
      manufactureYear: 2011,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'COLHEITADEIRA',
      currentValue: 700000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Colheitadeira',
      manufacturer: 'NEW HOLLAND 5090',
      manufactureYear: 2012,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CAMINHÃO TRATOR 510CV',
      currentValue: 600000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Caminhão',
      manufacturer: 'DAF',
      manufactureYear: 2020,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLANTADEIRA SEMEATO',
      currentValue: 40000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Plantadeira',
      manufacturer: 'SEMEATO',
      manufactureYear: 2008,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS 680',
      currentValue: 110000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Trator',
      manufacturer: 'MASSEY FERGUSON',
      manufactureYear: 1997,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS 265',
      currentValue: 40000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Trator',
      manufacturer: 'MASSEY FERGUSON',
      manufactureYear: 1986,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS',
      currentValue: 62961,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Trator',
      manufacturer: 'MASSEY FERGUSON',
      manufactureYear: 1995,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLANTADEIRA',
      currentValue: 150000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Plantadeira',
      manufacturer: 'JUMIL',
      manufactureYear: 2015,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CAMIONETE - HILUX',
      currentValue: 140000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Veículo',
      manufacturer: 'TOYOTA',
      manufactureYear: 2013,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'MOTO BROS',
      currentValue: 16000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Moto',
      manufacturer: 'HONDA',
      manufactureYear: 2017,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'BICAÇAMBA 7 EIXOS',
      currentValue: 230000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Carreta',
      manufacturer: 'RANDON',
      manufactureYear: 2010,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'GRADE ARADORA 14D - 36POL',
      currentValue: 55000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Arado',
      manufacturer: 'TATU',
      manufactureYear: 2015,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'MOTO - CG',
      currentValue: 7000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Moto',
      manufacturer: 'HONDA',
      manufactureYear: 2007,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PULVERIZADOR ARRASTO',
      currentValue: 40000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Pulverizador',
      manufacturer: 'JACTO',
      manufactureYear: 2010,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLANTADEIRA 22L',
      currentValue: 1000000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Plantadeira',
      manufacturer: 'JOHN DEERE',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'RODOCAÇAMBA 9 EIXOS',
      currentValue: 400000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Carreta',
      manufacturer: 'RANDOM',
      manufactureYear: 2022,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLATAFORMA COLHEITADEIRA',
      currentValue: 200000,
      status: '',
      owner: 'José Messias do Rego',
      type: 'Colheitadeira',
      manufacturer: 'NEW HOLLAND',
      manufactureYear: 2012,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'COLHEITADEIRA',
      currentValue: 350000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Colheitadeira',
      manufacturer: 'NEW HOLAND - TC5090',
      manufactureYear: 2012,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS',
      currentValue: 110000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Trator',
      manufacturer: 'NEW HOLAND - 7630',
      manufactureYear: 2011,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLANTADEIRA',
      currentValue: 700000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Plantadeira',
      manufacturer: 'JOHN DEERE',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PULVERIZADOR',
      currentValue: 380000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Pulverizador',
      manufacturer: 'JACTO - UNIPORTE 2500L',
      manufactureYear: 2008,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLANTADEIRA JUMIL 15L',
      currentValue: 180000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Plantadeira',
      manufacturer: 'JUMIL - JM3080',
      manufactureYear: 2015,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'TRATOR DE PNEUS',
      currentValue: 750000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Trator',
      manufacturer: 'JOHN DEERE - 7230J',
      manufactureYear: 2021,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PLATAFORMA DE COLHEITADEIRA - DRAPPER 35 PÉS',
      currentValue: 741000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Plataforma',
      manufacturer: 'JOHN DEERE',
      manufactureYear: 2023,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'DISTRIBUIDOR DE CALCÁRIO/ADUBO',
      currentValue: 100000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Distribuidor',
      manufacturer: 'PICCIN',
      manufactureYear: 2018,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'GRADE NIVELADORA - 72 DISCOS',
      currentValue: 115000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Grade',
      manufacturer: 'TATU',
      manufactureYear: 2022,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CARRETA CALDA PRONTA',
      currentValue: 180000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Carreta',
      manufacturer: 'IMEP - 11000 L',
      manufactureYear: 2014,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'GRADE ARADORA - 28 POL',
      currentValue: 48000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Grade',
      manufacturer: 'MARCHESAN',
      manufactureYear: 2014,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PÁ CARREGADEIRA',
      currentValue: 450000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Carregadeira',
      manufacturer: 'SDLG',
      manufactureYear: 2023,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'COLHEITADEIRA',
      currentValue: 3090000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Colheitadeira',
      manufacturer: 'JOHN DEERE',
      manufactureYear: 2023,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'PULVERIZADOR AUTOPROPELIDO',
      currentValue: 600000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Pulverizador',
      manufacturer: 'JOHN DEERE',
      manufactureYear: 2014,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'VEICULO UTILITÁRIO - RANGER',
      currentValue: 170000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Veículo',
      manufacturer: 'FORD',
      manufactureYear: 2018,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Bom',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
    {
      name: 'CONJUNTO GUINCHO',
      currentValue: 40000,
      status: '',
      owner: 'Gustavo Silveira Rego',
      type: 'Equipamento',
      manufacturer: 'BIG BAG',
      manufactureYear: 2023,
      avaliableAsCollateral: true,
      depreciationRate: 10,
      notes: 'Estado de Conservação: Ótimo',
      producer_id: 'cmb9pct8z002eqt7nu5ca2uru',
      active: true,
    },
  ]

  await prisma.immobilized.createMany({
    data: maquinario,
    skipDuplicates: true,
  })
}
